services:
  hwid-app:
    build: .
    container_name: hwid-app
    ports:
      - "8080:8080"
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: syntara
      MYSQL_USER: hwid
      MYSQL_PASSWORD: hwidpass
      BOT_TOKEN: ""
    volumes:
      - hwid-db:/var/lib/mysql
    restart: unless-stopped

volumes:
  hwid-db:

